# Generated by Django 3.0.8 on 2020-07-10 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Departure', models.CharField(max_length=20)),
                ('Arrival', models.CharField(max_length=20)),
                ('FlightDate', models.DateTimeField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('image', models.ImageField(default='default.jpg', upload_to='destination_pics')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Flights.Flight')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
